
package com.taggy.quickstart.demo.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TimeServer", targetNamespace = "http://quickstart.taggy.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface TimeServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://quickstart.taggy.com/TimeServer/getTimeAsStringRequest", output = "http://quickstart.taggy.com/TimeServer/getTimeAsStringResponse")
    public String getTimeAsString();

    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://quickstart.taggy.com/TimeServer/getTimeAsElapsedRequest", output = "http://quickstart.taggy.com/TimeServer/getTimeAsElapsedResponse")
    public long getTimeAsElapsed();

}
